# Generated by Django 4.2.5 on 2023-09-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='head_phones',
            table='job',
        ),
        migrations.AlterModelTable(
            name='phones',
            table='others',
        ),
        migrations.AlterModelTable(
            name='smart_watches',
            table='vegas_all',
        ),
    ]
